# name 可以自定义
name: Publish Electron App

# 触发条件：在 push 到 main 分支后，新的 Github 项目 应该都是 main，而之前的项目一般都是 master
on:
  push:
    branches:
      - main

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # 生成静态文件
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: npm run all:install && npm run all:publish
